version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "sonartoken"
    SONARQUBE_ENDPOINT: "endpoint"
    SONAR_ORG: "organization"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
  build:
    commands:
      - sonar-scanner -Dsonar.projectKey=sample-lambda-v2 -Dsonar.sources=. -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.organization=${SONAR_ORG} -Dsonar.host.url=${SONARQUBE_ENDPOINT}